### ISSUE TITLE
DMS2_batch_prefs MCMC does not converge on certain ENV sites

### ISSUE THREAD

**Issue by jiroop** [jbloomlab/phydms#16]
There is a readme file within the zipped folder that describes the issue in more detail and how to reproduce it, but this is the error I am getting when running DMS2_batch_prefs:

2018-11-02 13:35:54,248 - INFO - Getting results for site 206...
2018-11-02 13:35:54,248 - ERROR - Terminating dms2_prefs with ERROR
Traceback (most recent call last):
  File "/home/jroop/.local/bin/dms2_prefs", line 304, in main
    .format(r, logstring))
RuntimeError: Failed for site 206:
	Beginning MCMC at Fri Nov  2 11:59:53 2018
	After 4 MCMC chains each of 20000 steps, mean R = 1.2541643122083816 and mean Neff = 37.9
	MCMC failed to converge. Doing retry 1 with 40000 iterations per chain.
	After 4 MCMC chains each of 40000 steps, mean R = 1.539564031833223 and mean Neff = 23.35
	MCMC failed to converge. Doing retry 2 with 80000 iterations per chain.
	After 4 MCMC chains each of 80000 steps, mean R = 1.2654302097288201 and mean Neff = 33.2
	MCMC failed to converge. Doing retry 3 with 160000 iterations per chain.
	After 4 MCMC chains each of 160000 steps, mean R = 1.530588807580061 and mean Neff = 57.35
	MCMC failed to converge. Doing retry 4 with 320000 iterations per chain.
	After 4 MCMC chains each of 320000 steps, mean R = 1.2578045547551282 and mean Neff = 151.3
	MCMC failed to converge. Doing retry 5 with 640000 iterations per chain.
	After 4 MCMC chains each of 640000 steps, mean R = 1.5417707240750493 and mean Neff = 199.05
	MCMC FAILED to converge after all attempts at Fri Nov  2 13:35:52 2018.
[181101_MCMC_debug_short.tar.gz](https://github.com/jbloomlab/phydms/files/2544363/181101_MCMC_debug_short.tar.gz)

**Comment by jbloom** [comment]
@jiroop: This issue should be posted with the `dms_tools2` repo, not the `phydms` repo, since it affects the former.

I have closed issue, can you repost on `dms_tools2`.
