### ISSUE TITLE
phydms_plotselection

### ISSUE THREAD

**Issue by Hamil462** [jbloomlab/phydms#39]
Hi,
I am trying to run an analysis using phydms_plotselection after phydms but this program does not seem to be present in the repository, so I keep getting "no such file or directory" errors even after importing.  Where can I access this code?  Thanks.

**Comment by skhilton** [comment]
Thanks for your interest in `phydms`! 

`phydms_plotselection` is not a `phydms` function. You can use `phydms` to create logoplots using the script `phydms_logoplot` with documentation [here](http://jbloomlab.github.io/phydms/phydms_logoplot.html). Alternatively, the package [`dmslogo`](https://jbloomlab.github.io/dmslogo/index.html) is a more flexible tool for logoplots. If you provide me an example of the type of plot you are trying to create or recreate I might be able to provide more help!

**Comment by Hamil462** [comment]
Hi,
Thanks for replying!  phydms_plotselection definitely used to be a function as it was used by Jesse Bloom in the notebook found at https://github.com/jbloomlab/AtlasPaper_SUMO1_UBE2I_ExpCM/blob/master/SUMO_and_UBE2I_analysis.ipynb to plot sites with strong selective bias (the plots near the bottom of the page).
I know that the logoplots are useful for plotting amino acid frequency, but what might you suggest to represent selection if plotselection is no longer available?

________________________________

**Comment by jbloom** [comment]
It was in version 1.*, but is not part of version 2.*. If you want to use it, install version 1.*. Note however that we are no longer supporting that version.
