### ISSUE TITLE
Can phydms calculate dN/dS ratios for entire genes in phylogeny?

### ISSUE THREAD

**Issue by cahuparo** [jbloomlab/phydms#42]
Hi there, 

I wanted to ask if phydms could calculate dN/dS ratios of tree leaves? I work with intra-celullar immune receptors. I have sequence and annotate this gene family across several individuals (sweetpotato cultivars).  I generated amino acid phylogenies and now I am interested in improving my understanding of the phylogeny. I would like to color code my phylogeny based on genes that are experiencing diversifying selection. A dN/dS ratio for each gene would do the trick. However, I have tried running this on PAML and it has had issues with the number of sequences. If this is possible, I would like to give it a try. Would you recommend other software to accomplish this? Thanks

Camilo

**Comment by jbloom** [comment]
I'm not sure that `phydms` is appropriate for your problem unless you have deep mutational scanning data. I would recommend `HyPhy` or `DataMonkey`.
