### ISSUE TITLE
Typo in tutorial?

### ISSUE THREAD

**Issue by gavinmdouglas** [jbloomlab/phydms#45]
Hi there,

I believe this is a typo in the [tutorial](https://htmlpreview.github.io/?https://github.com/jbloomlab/phydms/blob/master/tutorial/phydms_tutorial.html):

```
df["preference"] = [max(minenrichment, (10**df["Trial_1_AmpConc_2500"][x] + 10**df["Trial_1_AmpConc_2500"][x])/2) for x in range(len(df))]
```

I'm assuming that line is meant to calculate the mean of the `Trial_1_AmpConc_2500` and `Trial_2_AmpConc_2500`, but `Trial_1_AmpConc_2500` is specified each time.

Cheers,

Gavin

**Comment by jbloom** [comment]
Yes, you are correct this is a typo, although it obviously only affects the tutorial, not the actual software package itself.

Thanks for catching this. Are you up for submitting a pull request to fix the tutorial typo?

**Comment by gavinmdouglas** [comment]
Sure, I just made a pull request: https://github.com/jbloomlab/phydms/pull/46
