### ISSUE TITLE
check `divPressureValues` in `ExpCM_empirical_phi_divpressure`

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/phydms#6]
@skhilton: Things are only guaranteed to work if the `divPressureValues` are normalized so that their absolute values are between 0 and 1. Otherwise you can end up with negative rates. But currently there is no check on these values in the `ExpCM_empirical_phi_divpressure` class `__init__` method.

Therefore, the method is not guaranteed to work. In practice the values may be checked in the program calling this class, but this is not guaranteed if the program is re-implemented so such a check should be added and the documentation should reflect this limit on the values.

This check can be instituted via `checkParam` as for `g` in `ExpCM_empirical_phi`.

**Comment by skhilton** [comment]
@jbloom: I added the check via an `assert` statement rather than `checkParam`.  I wasn't sure how to implement `checkParam` and define the `PARAMSIZE['deltar']` because the size of `deltar` is going to change with the size of the gene.
