### ISSUE TITLE
Underflow error with `YNGKP_M5`

### ISSUE THREAD

**Issue by skhilton** [jbloomlab/phydms#7]
Here are the input files and `phydms` command I used when I got the underflow error. 
[NP_phydms_comprehensive.zip](https://github.com/jbloomlab/phydms/files/778998/NP_phydms_comprehensive.zip)

**Comment by jbloom** [comment]
@skhilton: Can you re-attach the files for this bug report? You zipped the symbolic link to the data files rather than the actual files, so I can't run the program on them.

**Comment by skhilton** [comment]
@jbloom: Here are the actual files. Also, I have not tried re-running `phydms_comprehensive` on on this set so I don't know if it still throws an error. Let me know if you want me to do that. 
[NP_phydms_comprehensive.zip](https://github.com/jbloomlab/phydms/files/818271/NP_phydms_comprehensive.zip)

**Comment by jbloom** [comment]
Should be resolved by this commit:
https://github.com/jbloomlab/phydms/commit/7552690463e45a9b88a2ca7797d7ee959ee86277

The basic issue is that when there is a distribution model (such as YNGKP M5), underflow actually is OK for any given category at any given site as long as not all categories underflow at a site. The changes fix this.

@skhilton: Can you re-run on your computer and make sure that the error has gone away.
