### ISSUE TITLE
`--brlen` does not accept "fix" as an argument

### ISSUE THREAD

**Issue by skhilton** [jbloomlab/phydms#8]
command: ```phydms NP_data/NP_alignment.fasta NP_data/NP_tree.newick YNGKP_M0 testOut/ --brlen fix```

The data is the NP data in the `tests` directory. 

error:
```
File "/Users/sarah/Library/Python/3.5/lib/python/site-packages/phydms-2.0.dev0-py3.5-macosx-10.6-intel.egg/EGG-INFO/scripts/phydms", line 223, in main
    raise ValueError("Invalid brlen {0}".format(args['brlen']))
ValueError: Invalid brlen fix
```

**Comment by jbloom** [comment]
This is expected. I have removed the `fix` option for `--brlen`. The only two allowed options should now be `optimize` and `scale`. That's because it doesn't really make sense to fix the branch lengths -- we always want to at least scale them.
